version: "3.9"

services:
  server1:
    container_name: "server1"
    build: ./test_server/
    ports:
      - "8001:8001"
    environment:
      - PORT=8001

  server2:
    container_name: "server2"
    build: ./test_server/
    ports:
      - "8002:8002"
    environment:
      - PORT=8002

  server3:
    container_name: "server3"
    build: ./test_server/
    ports:
      - "8003:8003"
    environment:
      - PORT=8003