version: "3.9"

services:
  proxy:
    build: ./proxy            # директория с app.py и requirements.txt
    ports:
      - "8000:8000"
    environment:
      - DEFAULT_ALGORITHM=topsis
      - COLLECT_PERIOD=2
    depends_on:
      - svc_a
      - svc_b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # нужен collector’у

  svc_a:
    image: myorg/myapp:latest
    expose: [8080]
    environment:
      - NODE_ID=svc_a

  svc_b:
    image: myorg/myapp:latest
    expose: [8080]
    environment:
      - NODE_ID=svc_b
